---

- name: Install kubectl
  become: true
  yum:
    name: kubectl
    state: present

- name: Install AWS CLI dependencies
  become: true
  yum:
    name: python3-pip  # Install pip for Python packages
    state: present

- name: Install AWS CLI using pip
  become: true
  pip:
    name: awscli
    executable: pip3  # Specify pip3 for Python 3